[package]
name = "cobol-codegen"
version.workspace = true
edition.workspace = true

[dependencies]
cobol-common.workspace = true
cobol-hir.workspace = true
cobol-runtime.workspace = true
smol_str.workspace = true

[dev-dependencies]
cobol-lexer.workspace = true
cobol-parser.workspace = true
cobol-ast.workspace = true
tempfile.workspace = true
