[package]
name = "cobol-driver"
version.workspace = true
edition.workspace = true

[dependencies]
cobol-ast.workspace = true
cobol-common.workspace = true
cobol-diagnostics.workspace = true
cobol-preprocessor.workspace = true
cobol-lexer.workspace = true
cobol-parser.workspace = true
cobol-sema.workspace = true
cobol-hir.workspace = true
cobol-codegen.workspace = true
cobol-runtime.workspace = true
clap.workspace = true

[dev-dependencies]
cobol-ast.workspace = true
cobol-common.workspace = true
cobol-lexer.workspace = true
cobol-parser.workspace = true
cobol-sema.workspace = true
cobol-hir.workspace = true
cobol-codegen.workspace = true
tempfile.workspace = true
