// COBOL Compiler - Runtime support library
//
// This crate provides the runtime functions that are called from COBOL
// programs compiled to native code. All public functions use the C ABI
// so that they can be linked with code generated by the compiler backend.
//
// The runtime is compiled as both an rlib (for Rust-level testing and
// the CLI driver) and a staticlib (for linking with generated object
// files).

pub mod decimal;
pub mod display;
pub mod exception;
pub mod file_io;
pub mod intrinsic;
pub mod json;
pub mod national;
pub mod program;
pub mod screen;
pub mod sort_merge;
pub mod string_ops;
pub mod threading;
pub mod unicode;
pub mod xml;

#[cfg(test)]
mod tests {
    #[test]
    fn test_display_string_valid_utf8() {
        // Verify that cobol_display_string does not panic on valid UTF-8.
        let s = b"Hello, World!";
        unsafe {
            super::display::cobol_display_string(s.as_ptr(), s.len() as u32);
        }
    }

    #[test]
    fn test_display_int() {
        super::display::cobol_display_int(42);
        super::display::cobol_display_int(-1);
        super::display::cobol_display_int(0);
    }
}
