// COBOL Code Generation - C output backend
//
// Translates HIR into C source code that calls the COBOL runtime library.
// The generated C code is then compiled with clang/cc and linked against
// the runtime's static library to produce a native executable.

use cobol_hir::{
    HirBinOp, HirCompareOp, HirCondition, HirDataItem, HirExpr, HirLiteral, HirPerformKind,
    HirProgram, HirStatement, HirType, HirUnaryOp,
};

/// Generates C source code from a HIR program.
pub fn generate_c(program: &HirProgram) -> String {
    let mut out = String::new();

    // Header
    emit_header(&mut out);

    // Runtime function declarations
    emit_runtime_declarations(&mut out);

    // Global data items
    emit_data_items(&mut out, &program.data_items);

    // Main function
    out.push_str("int main(int argc, char** argv) {\n");

    // Initialize data items
    emit_data_init(&mut out, &program.data_items);

    // Emit body statements
    for stmt in &program.body {
        emit_statement(&mut out, stmt, 1);
    }

    // Fallthrough return
    out.push_str("    return 0;\n");
    out.push_str("}\n");

    out
}

fn emit_header(out: &mut String) {
    out.push_str("/* Generated by cobolc - COBOL Compiler */\n");
    out.push_str("#include <stdio.h>\n");
    out.push_str("#include <stdlib.h>\n");
    out.push_str("#include <string.h>\n");
    out.push_str("#include <stdint.h>\n");
    out.push('\n');
}

fn emit_runtime_declarations(out: &mut String) {
    out.push_str("/* Runtime library declarations */\n");
    out.push_str("extern void cobol_display_string(const uint8_t* ptr, uint32_t len);\n");
    out.push_str("extern void cobol_display_int(int64_t value);\n");
    out.push_str("extern void cobol_display_newline(void);\n");
    out.push_str("extern void cobol_display_space(void);\n");
    out.push_str("extern void cobol_display_flush(void);\n");
    out.push_str("extern void cobol_stop_run(void) __attribute__((noreturn));\n");
    out.push_str("extern void cobol_goback(void) __attribute__((noreturn));\n");
    out.push('\n');
}

fn emit_data_items(out: &mut String, items: &[HirDataItem]) {
    if items.is_empty() {
        return;
    }
    out.push_str("/* Data items */\n");
    for item in items {
        let c_name = sanitize_name(&item.name);
        match &item.data_type {
            HirType::Alphanumeric { size } => {
                out.push_str(&format!("static char {}[{}];\n", c_name, size + 1));
            }
            HirType::Numeric { .. } => {
                out.push_str(&format!("static int64_t {};\n", c_name));
            }
            HirType::Index => {
                out.push_str(&format!("static int64_t {};\n", c_name));
            }
            HirType::Pointer => {
                out.push_str(&format!("static void* {};\n", c_name));
            }
        }
    }
    out.push('\n');
}

fn emit_data_init(out: &mut String, items: &[HirDataItem]) {
    for item in items {
        let c_name = sanitize_name(&item.name);
        if let Some(init) = &item.initial_value {
            match (&item.data_type, init) {
                (HirType::Alphanumeric { size }, HirLiteral::String(s)) => {
                    let escaped = escape_c_string(s);
                    out.push_str(&format!(
                        "    memset({c_name}, ' ', {size});\n    strncpy({c_name}, \"{escaped}\", {size});\n    {c_name}[{size}] = '\\0';\n"
                    ));
                }
                (HirType::Alphanumeric { size }, HirLiteral::Space) => {
                    out.push_str(&format!(
                        "    memset({c_name}, ' ', {size});\n    {c_name}[{size}] = '\\0';\n"
                    ));
                }
                (HirType::Alphanumeric { size }, HirLiteral::Zero) => {
                    out.push_str(&format!(
                        "    memset({c_name}, '0', {size});\n    {c_name}[{size}] = '\\0';\n"
                    ));
                }
                (HirType::Numeric { .. } | HirType::Index, HirLiteral::Integer(n)) => {
                    out.push_str(&format!("    {c_name} = {n};\n"));
                }
                (HirType::Numeric { .. } | HirType::Index, HirLiteral::Zero) => {
                    out.push_str(&format!("    {c_name} = 0;\n"));
                }
                _ => {
                    // Default initialization
                    match &item.data_type {
                        HirType::Alphanumeric { size } => {
                            out.push_str(&format!(
                                "    memset({c_name}, ' ', {size});\n    {c_name}[{size}] = '\\0';\n"
                            ));
                        }
                        _ => {
                            out.push_str(&format!("    {c_name} = 0;\n"));
                        }
                    }
                }
            }
        } else {
            // Default initialization for items without VALUE clause
            match &item.data_type {
                HirType::Alphanumeric { size } => {
                    out.push_str(&format!(
                        "    memset({c_name}, ' ', {size});\n    {c_name}[{size}] = '\\0';\n"
                    ));
                }
                HirType::Numeric { .. } | HirType::Index => {
                    out.push_str(&format!("    {c_name} = 0;\n"));
                }
                HirType::Pointer => {
                    out.push_str(&format!("    {c_name} = NULL;\n"));
                }
            }
        }
    }
}

fn emit_statement(out: &mut String, stmt: &HirStatement, indent: usize) {
    let pad = "    ".repeat(indent);
    match stmt {
        HirStatement::Display {
            operands,
            no_advancing,
            ..
        } => {
            for (i, op) in operands.iter().enumerate() {
                if i > 0 {
                    // COBOL DISPLAY separates operands with a space by default
                    // (some implementations don't; we follow the common convention)
                }
                emit_display_operand(out, op, &pad);
            }
            if !no_advancing {
                out.push_str(&format!("{pad}cobol_display_newline();\n"));
            } else {
                out.push_str(&format!("{pad}cobol_display_flush();\n"));
            }
        }
        HirStatement::Move { from, to, .. } => {
            // Simplified: generate assignment for each target
            for target in to {
                let c_target = sanitize_name(target);
                emit_move_to(out, from, &c_target, &pad);
            }
        }
        HirStatement::Compute { target, expr, .. } => {
            let c_target = sanitize_name(target);
            let c_expr = emit_expr(expr);
            out.push_str(&format!("{pad}{c_target} = {c_expr};\n"));
        }
        HirStatement::Add { operands, to, .. } => {
            for target in to {
                let c_target = sanitize_name(target);
                let sum: Vec<_> = operands.iter().map(emit_expr).collect();
                let sum_expr = sum.join(" + ");
                out.push_str(&format!("{pad}{c_target} += {sum_expr};\n"));
            }
        }
        HirStatement::Subtract {
            operands, from, ..
        } => {
            for target in from {
                let c_target = sanitize_name(target);
                let sum: Vec<_> = operands.iter().map(emit_expr).collect();
                let sum_expr = sum.join(" + ");
                out.push_str(&format!("{pad}{c_target} -= ({sum_expr});\n"));
            }
        }
        HirStatement::If {
            condition,
            then_body,
            else_body,
            ..
        } => {
            let cond = emit_condition(condition);
            out.push_str(&format!("{pad}if ({cond}) {{\n"));
            for s in then_body {
                emit_statement(out, s, indent + 1);
            }
            if !else_body.is_empty() {
                out.push_str(&format!("{pad}}} else {{\n"));
                for s in else_body {
                    emit_statement(out, s, indent + 1);
                }
            }
            out.push_str(&format!("{pad}}}\n"));
        }
        HirStatement::Perform { kind, .. } => {
            emit_perform(out, kind, indent);
        }
        HirStatement::Call { program, params: _, .. } => {
            out.push_str(&format!("{pad}/* CALL {} -- not yet implemented */\n", emit_expr(program)));
        }
        HirStatement::StopRun { .. } => {
            out.push_str(&format!("{pad}cobol_stop_run();\n"));
        }
        HirStatement::Goback { .. } => {
            out.push_str(&format!("{pad}cobol_goback();\n"));
        }
        HirStatement::Continue { .. } => {
            out.push_str(&format!("{pad}/* CONTINUE */\n"));
        }
    }
}

fn emit_display_operand(out: &mut String, expr: &HirExpr, pad: &str) {
    match expr {
        HirExpr::Literal(HirLiteral::String(s)) => {
            let escaped = escape_c_string(s);
            let len = s.len();
            out.push_str(&format!(
                "{pad}cobol_display_string((const uint8_t*)\"{escaped}\", {len});\n"
            ));
        }
        HirExpr::Literal(HirLiteral::Integer(n)) => {
            out.push_str(&format!("{pad}cobol_display_int({n});\n"));
        }
        HirExpr::Literal(HirLiteral::Zero) => {
            out.push_str(&format!("{pad}cobol_display_int(0);\n"));
        }
        HirExpr::Literal(HirLiteral::Space) => {
            out.push_str(&format!("{pad}cobol_display_space();\n"));
        }
        HirExpr::Literal(HirLiteral::Decimal(d)) => {
            let escaped = escape_c_string(d);
            let len = d.len();
            out.push_str(&format!(
                "{pad}cobol_display_string((const uint8_t*)\"{escaped}\", {len});\n"
            ));
        }
        HirExpr::Variable(name) => {
            let c_name = sanitize_name(name);
            // We don't know the type at this point, so generate a generic display.
            // For simplicity, display as integer. A full implementation would
            // look up the type.
            out.push_str(&format!("{pad}cobol_display_int({c_name});\n"));
        }
        HirExpr::BinaryOp { .. } | HirExpr::UnaryOp { .. } => {
            let e = emit_expr(expr);
            out.push_str(&format!("{pad}cobol_display_int({e});\n"));
        }
    }
}

fn emit_move_to(out: &mut String, from: &HirExpr, c_target: &str, pad: &str) {
    // Simplified move: assign value to target
    match from {
        HirExpr::Literal(HirLiteral::String(s)) => {
            let escaped = escape_c_string(s);
            out.push_str(&format!(
                "{pad}strncpy({c_target}, \"{escaped}\", sizeof({c_target}) - 1);\n"
            ));
            out.push_str(&format!(
                "{pad}{c_target}[sizeof({c_target}) - 1] = '\\0';\n"
            ));
        }
        HirExpr::Literal(HirLiteral::Integer(n)) => {
            out.push_str(&format!("{pad}{c_target} = {n};\n"));
        }
        HirExpr::Literal(HirLiteral::Zero) => {
            out.push_str(&format!("{pad}{c_target} = 0;\n"));
        }
        HirExpr::Literal(HirLiteral::Space) => {
            out.push_str(&format!(
                "{pad}memset({c_target}, ' ', sizeof({c_target}) - 1);\n"
            ));
            out.push_str(&format!(
                "{pad}{c_target}[sizeof({c_target}) - 1] = '\\0';\n"
            ));
        }
        _ => {
            let e = emit_expr(from);
            out.push_str(&format!("{pad}{c_target} = {e};\n"));
        }
    }
}

fn emit_perform(out: &mut String, kind: &HirPerformKind, indent: usize) {
    let pad = "    ".repeat(indent);
    match kind {
        HirPerformKind::Inline { body } => {
            out.push_str(&format!("{pad}{{\n"));
            for s in body {
                emit_statement(out, s, indent + 1);
            }
            out.push_str(&format!("{pad}}}\n"));
        }
        HirPerformKind::Times { count, body } => {
            let c_count = emit_expr(count);
            out.push_str(&format!(
                "{pad}for (int64_t _cobol_i = 0; _cobol_i < ({c_count}); _cobol_i++) {{\n"
            ));
            for s in body {
                emit_statement(out, s, indent + 1);
            }
            out.push_str(&format!("{pad}}}\n"));
        }
        HirPerformKind::Until { condition, body } => {
            let cond = emit_condition(condition);
            out.push_str(&format!("{pad}while (!({cond})) {{\n"));
            for s in body {
                emit_statement(out, s, indent + 1);
            }
            out.push_str(&format!("{pad}}}\n"));
        }
        HirPerformKind::Varying {
            var,
            from,
            by,
            until,
            body,
        } => {
            let c_var = sanitize_name(var);
            let c_from = emit_expr(from);
            let c_by = emit_expr(by);
            let cond = emit_condition(until);
            out.push_str(&format!(
                "{pad}{c_var} = {c_from};\n{pad}while (!({cond})) {{\n"
            ));
            for s in body {
                emit_statement(out, s, indent + 1);
            }
            out.push_str(&format!("{pad}    {c_var} += {c_by};\n"));
            out.push_str(&format!("{pad}}}\n"));
        }
        HirPerformKind::ProcedureName { name } => {
            let c_name = sanitize_name(name);
            out.push_str(&format!(
                "{pad}/* PERFORM {c_name} -- procedure calls not yet implemented */\n"
            ));
        }
    }
}

fn emit_expr(expr: &HirExpr) -> String {
    match expr {
        HirExpr::Literal(HirLiteral::Integer(n)) => format!("((int64_t){n})"),
        HirExpr::Literal(HirLiteral::Decimal(d)) => d.to_string(),
        HirExpr::Literal(HirLiteral::String(s)) => {
            // Strings in expression context are unusual; use 0
            format!("0 /* string literal: {} */", escape_c_string(s))
        }
        HirExpr::Literal(HirLiteral::Zero) => "((int64_t)0)".to_string(),
        HirExpr::Literal(HirLiteral::Space) => "((int64_t)32)".to_string(),
        HirExpr::Variable(name) => sanitize_name(name),
        HirExpr::BinaryOp { op, left, right } => {
            let l = emit_expr(left);
            let r = emit_expr(right);
            let op_str = match op {
                HirBinOp::Add => "+",
                HirBinOp::Sub => "-",
                HirBinOp::Mul => "*",
                HirBinOp::Div => "/",
                HirBinOp::Pow => return format!("/* pow */ (int64_t)1 /* {l} ** {r} */"),
            };
            format!("({l} {op_str} {r})")
        }
        HirExpr::UnaryOp { op, operand } => {
            let o = emit_expr(operand);
            match op {
                HirUnaryOp::Neg => format!("(-{o})"),
            }
        }
    }
}

fn emit_condition(cond: &HirCondition) -> String {
    match cond {
        HirCondition::Compare { left, op, right } => {
            let l = emit_expr(left);
            let r = emit_expr(right);
            let op_str = match op {
                HirCompareOp::Eq => "==",
                HirCompareOp::Ne => "!=",
                HirCompareOp::Gt => ">",
                HirCompareOp::Lt => "<",
                HirCompareOp::Ge => ">=",
                HirCompareOp::Le => "<=",
            };
            format!("({l} {op_str} {r})")
        }
        HirCondition::And(a, b) => {
            let a = emit_condition(a);
            let b = emit_condition(b);
            format!("({a} && {b})")
        }
        HirCondition::Or(a, b) => {
            let a = emit_condition(a);
            let b = emit_condition(b);
            format!("({a} || {b})")
        }
        HirCondition::Not(inner) => {
            let c = emit_condition(inner);
            format!("(!{c})")
        }
    }
}

/// Convert a COBOL data name to a valid C identifier.
///
/// COBOL names use hyphens which are not valid in C, so we replace
/// them with underscores.
fn sanitize_name(name: &str) -> String {
    name.replace('-', "_")
}

/// Escape special characters for use in a C string literal.
fn escape_c_string(s: &str) -> String {
    let mut escaped = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '\\' => escaped.push_str("\\\\"),
            '"' => escaped.push_str("\\\""),
            '\n' => escaped.push_str("\\n"),
            '\r' => escaped.push_str("\\r"),
            '\t' => escaped.push_str("\\t"),
            '\0' => escaped.push_str("\\0"),
            c => escaped.push(c),
        }
    }
    escaped
}

/// Compile a generated C source file into a native executable.
///
/// Returns `Ok(())` on success, or an error message on failure.
pub fn compile_c_to_executable(
    c_source_path: &std::path::Path,
    output_path: &std::path::Path,
    runtime_lib_path: &std::path::Path,
) -> Result<(), String> {
    // Try clang first, then cc
    let compiler = find_c_compiler()?;

    let status = std::process::Command::new(&compiler)
        .arg(c_source_path)
        .arg("-o")
        .arg(output_path)
        .arg(format!("-L{}", runtime_lib_path.display()))
        .arg("-lcobol_runtime")
        .arg("-lpthread")
        .arg("-ldl")
        .arg("-lm")
        .status()
        .map_err(|e| format!("Failed to run C compiler '{}': {}", compiler, e))?;

    if status.success() {
        Ok(())
    } else {
        Err(format!(
            "C compiler '{}' exited with status: {}",
            compiler,
            status
        ))
    }
}

fn find_c_compiler() -> Result<String, String> {
    // Check CC environment variable
    if let Ok(cc) = std::env::var("CC") {
        return Ok(cc);
    }

    // Try clang, then gcc, then cc
    for compiler in &["clang", "gcc", "cc"] {
        if std::process::Command::new(compiler)
            .arg("--version")
            .output()
            .is_ok()
        {
            return Ok(compiler.to_string());
        }
    }

    Err("No C compiler found. Install clang or gcc.".to_string())
}

#[cfg(test)]
mod tests {
    use super::*;
    use cobol_common::{FileId, SourceFormat};
    use cobol_hir::lower_to_hir;
    use cobol_lexer::Lexer;
    use cobol_parser::Parser;

    fn parse_lower_generate(source: &str) -> String {
        let mut lexer = Lexer::new(source, FileId(0), SourceFormat::Free);
        let tokens = lexer.lex_all();
        let mut parser = Parser::new(tokens, FileId(0));
        let program = parser.parse_program().unwrap();
        let hir = lower_to_hir(&program);
        generate_c(&hir)
    }

    #[test]
    fn test_generate_hello_world() {
        let src = "\
IDENTIFICATION DIVISION.
PROGRAM-ID. HELLO-WORLD.
PROCEDURE DIVISION.
    DISPLAY \"Hello, World!\".
    STOP RUN.
";
        let c_code = parse_lower_generate(src);
        assert!(c_code.contains("cobol_display_string"));
        assert!(c_code.contains("Hello, World!"));
        assert!(c_code.contains("cobol_display_newline"));
        assert!(c_code.contains("cobol_stop_run"));
        assert!(c_code.contains("int main"));
    }

    #[test]
    fn test_generate_with_data_items() {
        let src = "\
IDENTIFICATION DIVISION.
PROGRAM-ID. TEST-DATA.
DATA DIVISION.
WORKING-STORAGE SECTION.
01  WS-NAME PIC X(20).
01  WS-COUNT PIC 9(5).
PROCEDURE DIVISION.
    DISPLAY WS-COUNT.
    STOP RUN.
";
        let c_code = parse_lower_generate(src);
        assert!(c_code.contains("static char WS_NAME"));
        assert!(c_code.contains("static int64_t WS_COUNT"));
    }

    #[test]
    fn test_sanitize_name() {
        assert_eq!(sanitize_name("WS-NAME"), "WS_NAME");
        assert_eq!(sanitize_name("HELLO-WORLD"), "HELLO_WORLD");
        assert_eq!(sanitize_name("SIMPLE"), "SIMPLE");
    }

    #[test]
    fn test_escape_c_string() {
        assert_eq!(escape_c_string("hello"), "hello");
        assert_eq!(escape_c_string("say \"hi\""), "say \\\"hi\\\"");
        assert_eq!(escape_c_string("a\\b"), "a\\\\b");
    }

    #[test]
    fn test_generate_if_statement() {
        let src = "\
IDENTIFICATION DIVISION.
PROGRAM-ID. TEST-IF.
DATA DIVISION.
WORKING-STORAGE SECTION.
01  WS-A PIC 9(3).
PROCEDURE DIVISION.
    IF WS-A > 100
        DISPLAY \"BIG\"
    ELSE
        DISPLAY \"SMALL\"
    END-IF.
    STOP RUN.
";
        let c_code = parse_lower_generate(src);
        assert!(c_code.contains("if ("));
        assert!(c_code.contains("} else {"));
    }
}
