// COBOL Code Generation - C output backend
//
// Translates HIR into C source code that calls the COBOL runtime library.
// The generated C code is then compiled with clang/cc and linked against
// the runtime's static library to produce a native executable.

use cobol_hir::{
    HirBinOp, HirCompareOp, HirCondition, HirDataItem, HirExpr, HirLiteral, HirOpenMode,
    HirPerformKind, HirProgram, HirStatement, HirType, HirUnaryOp,
};

/// Generates C source code from a HIR program.
pub fn generate_c(program: &HirProgram) -> String {
    let mut out = String::new();

    // Header
    emit_header(&mut out);

    // Runtime function declarations
    emit_runtime_declarations(&mut out);

    // Global data items
    emit_data_items(&mut out, &program.data_items);

    // COBOL 2002+: Emit class definitions (struct + vtable)
    emit_classes(&mut out, &program.classes);

    // COBOL 2002+: Emit user-defined function definitions
    emit_functions(&mut out, &program.functions);

    // COBOL 2014+: Emit type definitions
    emit_typedefs(&mut out, &program.typedefs);

    // COBOL 2023+: Emit interface definitions
    emit_interfaces(&mut out, &program.interfaces);

    // Main function
    out.push_str("int main(int argc, char** argv) {\n");

    // Initialize data items
    emit_data_init(&mut out, &program.data_items);

    // Emit body statements
    for stmt in &program.body {
        emit_statement(&mut out, stmt, 1);
    }

    // Fallthrough return
    out.push_str("    return 0;\n");
    out.push_str("}\n");

    out
}

fn emit_header(out: &mut String) {
    out.push_str("/* Generated by cobolc - COBOL Compiler */\n");
    out.push_str("#include <stdio.h>\n");
    out.push_str("#include <stdlib.h>\n");
    out.push_str("#include <string.h>\n");
    out.push_str("#include <stdint.h>\n");
    out.push_str("#include <setjmp.h>\n");
    out.push('\n');
}

fn emit_runtime_declarations(out: &mut String) {
    out.push_str("/* Runtime library declarations */\n");
    out.push_str("extern void cobol_display_string(const uint8_t* ptr, uint32_t len);\n");
    out.push_str("extern void cobol_display_int(int64_t value);\n");
    out.push_str("extern void cobol_display_newline(void);\n");
    out.push_str("extern void cobol_display_space(void);\n");
    out.push_str("extern void cobol_display_flush(void);\n");
    out.push_str("extern void cobol_stop_run(void) __attribute__((noreturn));\n");
    out.push_str("extern void cobol_goback(void) __attribute__((noreturn));\n");
    out.push_str("/* COBOL 2002+ runtime declarations */\n");
    out.push_str(
        "extern void cobol_raise(const char* exception_name) __attribute__((noreturn));\n",
    );
    out.push_str("extern void cobol_resume(const char* target);\n");
    out.push_str(
        "extern int64_t cobol_invoke(void* obj, const char* method, int64_t* args, int32_t argc);\n",
    );
    out.push_str("/* COBOL 2014+ runtime declarations */\n");
    out.push_str("extern void cobol_validate(const char* target_name);\n");
    out.push_str(
        "extern uint32_t cobol_json_generate(const void* fields, uint32_t field_count, uint8_t* output, uint32_t output_len);\n",
    );
    out.push_str(
        "extern uint32_t cobol_json_parse(const uint8_t* json, uint32_t json_len, void* fields, uint32_t field_count);\n",
    );
    out.push_str(
        "extern uint32_t cobol_xml_generate(const void* fields, uint32_t field_count, const uint8_t* root_name, uint32_t root_name_len, uint8_t* output, uint32_t output_len);\n",
    );
    out.push_str(
        "extern uint32_t cobol_xml_parse(const uint8_t* xml, uint32_t xml_len, void (*callback)(uint32_t, const uint8_t*, uint32_t, const uint8_t*, uint32_t));\n",
    );
    out.push_str("/* COBOL 2023+ runtime declarations */\n");
    out.push_str("extern uint32_t cobol_utf8_char_count(const uint8_t* ptr, uint32_t byte_len);\n");
    out.push_str(
        "extern uint32_t cobol_utf8_substring(const uint8_t* src, uint32_t src_len, uint32_t start_char, uint32_t char_count, uint8_t* dst, uint32_t dst_len);\n",
    );
    out.push_str("extern uint32_t cobol_utf8_upper(uint8_t* ptr, uint32_t byte_len);\n");
    out.push_str("extern uint32_t cobol_utf8_lower(uint8_t* ptr, uint32_t byte_len);\n");
    out.push_str("extern uint64_t cobol_thread_create(void (*func)(void*), void* arg);\n");
    out.push_str("extern uint32_t cobol_thread_join(uint64_t handle);\n");
    out.push_str("extern uint64_t cobol_mutex_create(void);\n");
    out.push_str("extern void cobol_mutex_lock(uint64_t handle);\n");
    out.push_str("extern void cobol_mutex_unlock(uint64_t handle);\n");
    out.push_str("extern void cobol_mutex_destroy(uint64_t handle);\n");
    out.push('\n');
}

fn emit_data_items(out: &mut String, items: &[HirDataItem]) {
    if items.is_empty() {
        return;
    }
    out.push_str("/* Data items */\n");
    for item in items {
        emit_single_data_item(out, item);
    }
    out.push('\n');
}

fn emit_single_data_item(out: &mut String, item: &HirDataItem) {
    let c_name = sanitize_name(&item.name);
    match &item.data_type {
        HirType::Alphanumeric { size } => {
            out.push_str(&format!("static char {}[{}];\n", c_name, size + 1));
        }
        HirType::Numeric { .. } => {
            out.push_str(&format!("static int64_t {};\n", c_name));
        }
        HirType::Group { members, .. } => {
            // Emit each member as a separate global variable (flattened)
            out.push_str(&format!("/* Group: {} */\n", c_name));
            for member in members {
                emit_single_data_item(out, member);
            }
        }
        HirType::Comp3 { .. } => {
            // Packed decimal stored as int64_t (simplified)
            out.push_str(&format!("static int64_t {};\n", c_name));
        }
        HirType::Binary { .. } => {
            out.push_str(&format!("static int64_t {};\n", c_name));
        }
        HirType::Index => {
            out.push_str(&format!("static int64_t {};\n", c_name));
        }
        HirType::Pointer => {
            out.push_str(&format!("static void* {};\n", c_name));
        }
        HirType::Boolean => {
            out.push_str(&format!("static int8_t {};\n", c_name));
        }
        HirType::FloatShort => {
            out.push_str(&format!("static float {};\n", c_name));
        }
        HirType::FloatLong => {
            out.push_str(&format!("static double {};\n", c_name));
        }
        HirType::FloatExtended => {
            out.push_str(&format!("static long double {};\n", c_name));
        }
    }
}

fn emit_data_init(out: &mut String, items: &[HirDataItem]) {
    for item in items {
        emit_single_data_init(out, item);
    }
}

fn emit_single_data_init(out: &mut String, item: &HirDataItem) {
    let c_name = sanitize_name(&item.name);
    if let HirType::Group { members, .. } = &item.data_type {
        // Initialize group members recursively
        for member in members {
            emit_single_data_init(out, member);
        }
        return;
    }
    if let Some(init) = &item.initial_value {
        match (&item.data_type, init) {
            (HirType::Alphanumeric { size }, HirLiteral::String(s)) => {
                let escaped = escape_c_string(s);
                out.push_str(&format!(
                    "    memset({c_name}, ' ', {size});\n    strncpy({c_name}, \"{escaped}\", {size});\n    {c_name}[{size}] = '\\0';\n"
                ));
            }
            (HirType::Alphanumeric { size }, HirLiteral::Space) => {
                out.push_str(&format!(
                    "    memset({c_name}, ' ', {size});\n    {c_name}[{size}] = '\\0';\n"
                ));
            }
            (HirType::Alphanumeric { size }, HirLiteral::Zero) => {
                out.push_str(&format!(
                    "    memset({c_name}, '0', {size});\n    {c_name}[{size}] = '\\0';\n"
                ));
            }
            (
                HirType::Numeric { .. }
                | HirType::Index
                | HirType::Comp3 { .. }
                | HirType::Binary { .. }
                | HirType::Boolean
                | HirType::FloatShort
                | HirType::FloatLong
                | HirType::FloatExtended,
                HirLiteral::Integer(n),
            ) => {
                out.push_str(&format!("    {c_name} = {n};\n"));
            }
            (
                HirType::Numeric { .. }
                | HirType::Index
                | HirType::Comp3 { .. }
                | HirType::Binary { .. }
                | HirType::Boolean
                | HirType::FloatShort
                | HirType::FloatLong
                | HirType::FloatExtended,
                HirLiteral::Zero,
            ) => {
                out.push_str(&format!("    {c_name} = 0;\n"));
            }
            _ => {
                emit_default_init(out, &item.data_type, &c_name);
            }
        }
    } else {
        emit_default_init(out, &item.data_type, &c_name);
    }
}

fn emit_default_init(out: &mut String, data_type: &HirType, c_name: &str) {
    match data_type {
        HirType::Alphanumeric { size } => {
            out.push_str(&format!(
                "    memset({c_name}, ' ', {size});\n    {c_name}[{size}] = '\\0';\n"
            ));
        }
        HirType::Numeric { .. }
        | HirType::Index
        | HirType::Comp3 { .. }
        | HirType::Binary { .. }
        | HirType::Boolean => {
            out.push_str(&format!("    {c_name} = 0;\n"));
        }
        HirType::FloatShort | HirType::FloatLong | HirType::FloatExtended => {
            out.push_str(&format!("    {c_name} = 0.0;\n"));
        }
        HirType::Pointer => {
            out.push_str(&format!("    {c_name} = NULL;\n"));
        }
        HirType::Group { members, .. } => {
            for member in members {
                emit_single_data_init(out, member);
            }
        }
    }
}

fn emit_statement(out: &mut String, stmt: &HirStatement, indent: usize) {
    let pad = "    ".repeat(indent);
    match stmt {
        HirStatement::Display {
            operands,
            no_advancing,
            ..
        } => {
            for (i, op) in operands.iter().enumerate() {
                if i > 0 {
                    // COBOL DISPLAY separates operands with a space by default
                    // (some implementations don't; we follow the common convention)
                }
                emit_display_operand(out, op, &pad);
            }
            if !no_advancing {
                out.push_str(&format!("{pad}cobol_display_newline();\n"));
            } else {
                out.push_str(&format!("{pad}cobol_display_flush();\n"));
            }
        }
        HirStatement::Move { from, to, .. } => {
            // Simplified: generate assignment for each target
            for target in to {
                let c_target = sanitize_name(target);
                emit_move_to(out, from, &c_target, &pad);
            }
        }
        HirStatement::Compute { target, expr, .. } => {
            let c_target = sanitize_name(target);
            let c_expr = emit_expr(expr);
            out.push_str(&format!("{pad}{c_target} = {c_expr};\n"));
        }
        HirStatement::Add { operands, to, .. } => {
            for target in to {
                let c_target = sanitize_name(target);
                let sum: Vec<_> = operands.iter().map(emit_expr).collect();
                let sum_expr = sum.join(" + ");
                out.push_str(&format!("{pad}{c_target} += {sum_expr};\n"));
            }
        }
        HirStatement::Subtract { operands, from, .. } => {
            for target in from {
                let c_target = sanitize_name(target);
                let sum: Vec<_> = operands.iter().map(emit_expr).collect();
                let sum_expr = sum.join(" + ");
                out.push_str(&format!("{pad}{c_target} -= ({sum_expr});\n"));
            }
        }
        HirStatement::If {
            condition,
            then_body,
            else_body,
            ..
        } => {
            let cond = emit_condition(condition);
            out.push_str(&format!("{pad}if ({cond}) {{\n"));
            for s in then_body {
                emit_statement(out, s, indent + 1);
            }
            if !else_body.is_empty() {
                out.push_str(&format!("{pad}}} else {{\n"));
                for s in else_body {
                    emit_statement(out, s, indent + 1);
                }
            }
            out.push_str(&format!("{pad}}}\n"));
        }
        HirStatement::Perform { kind, .. } => {
            emit_perform(out, kind, indent);
        }
        HirStatement::Multiply { operand, by, .. } => {
            for target in by {
                let c_target = sanitize_name(target);
                let c_operand = emit_expr(operand);
                out.push_str(&format!("{pad}{c_target} *= {c_operand};\n"));
            }
        }
        HirStatement::Divide {
            operand,
            into,
            remainder,
            ..
        } => {
            let c_operand = emit_expr(operand);
            for target in into {
                let c_target = sanitize_name(target);
                if let Some(rem) = remainder {
                    let c_rem = sanitize_name(rem);
                    out.push_str(&format!("{pad}{c_rem} = {c_target} %% {c_operand};\n"));
                }
                out.push_str(&format!("{pad}{c_target} /= {c_operand};\n"));
            }
        }
        HirStatement::Call {
            program, params, ..
        } => {
            let prog = emit_expr(program);
            let args: Vec<_> = params.iter().map(emit_expr).collect();
            out.push_str(&format!("{pad}/* CALL {prog}({}) */\n", args.join(", ")));
        }
        HirStatement::Open { entries, .. } => {
            for entry in entries {
                let c_name = sanitize_name(&entry.file_name);
                let mode_str = match entry.mode {
                    HirOpenMode::Input => "INPUT",
                    HirOpenMode::Output => "OUTPUT",
                    HirOpenMode::IoMode => "I-O",
                    HirOpenMode::Extend => "EXTEND",
                };
                out.push_str(&format!("{pad}/* OPEN {mode_str} {c_name} */\n"));
            }
        }
        HirStatement::Close { files, .. } => {
            for file in files {
                let c_name = sanitize_name(file);
                out.push_str(&format!("{pad}/* CLOSE {c_name} */\n"));
            }
        }
        HirStatement::Read {
            file_name,
            at_end,
            not_at_end,
            ..
        } => {
            let c_name = sanitize_name(file_name);
            out.push_str(&format!("{pad}/* READ {c_name} */\n"));
            if !at_end.is_empty() {
                out.push_str(&format!("{pad}/* AT END */\n"));
                for s in at_end {
                    emit_statement(out, s, indent + 1);
                }
            }
            if !not_at_end.is_empty() {
                out.push_str(&format!("{pad}/* NOT AT END */\n"));
                for s in not_at_end {
                    emit_statement(out, s, indent + 1);
                }
            }
        }
        HirStatement::Write { record_name, .. } => {
            let c_name = sanitize_name(record_name);
            out.push_str(&format!("{pad}/* WRITE {c_name} */\n"));
        }
        HirStatement::Rewrite { record_name, .. } => {
            let c_name = sanitize_name(record_name);
            out.push_str(&format!("{pad}/* REWRITE {c_name} */\n"));
        }
        HirStatement::Delete { file_name, .. } => {
            let c_name = sanitize_name(file_name);
            out.push_str(&format!("{pad}/* DELETE {c_name} */\n"));
        }
        HirStatement::GoTo {
            targets,
            depending_on,
            ..
        } => {
            if let Some(dep) = depending_on {
                let c_dep = sanitize_name(dep);
                out.push_str(&format!("{pad}/* GO TO DEPENDING ON {c_dep} */\n"));
            } else if let Some(target) = targets.first() {
                let c_target = sanitize_name(target);
                out.push_str(&format!("{pad}goto label_{c_target};\n"));
            }
        }
        HirStatement::Initialize { targets, .. } => {
            for target in targets {
                let c_target = sanitize_name(target);
                out.push_str(&format!("{pad}{c_target} = 0; /* INITIALIZE */\n"));
            }
        }
        HirStatement::Set { targets, value, .. } => {
            let c_value = emit_expr(value);
            for target in targets {
                let c_target = sanitize_name(target);
                out.push_str(&format!("{pad}{c_target} = {c_value};\n"));
            }
        }
        HirStatement::StringStmt { into, sources, .. } => {
            let c_into = sanitize_name(into);
            out.push_str(&format!("{pad}/* STRING INTO {c_into} */\n"));
            for src in sources {
                let _c_src = emit_expr(src);
            }
        }
        HirStatement::UnstringStmt { source, into, .. } => {
            let c_source = sanitize_name(source);
            let targets: Vec<_> = into.iter().map(|s| sanitize_name(s)).collect();
            out.push_str(&format!(
                "{pad}/* UNSTRING {c_source} INTO {} */\n",
                targets.join(", ")
            ));
        }
        HirStatement::Accept { target, .. } => {
            let c_target = sanitize_name(target);
            out.push_str(&format!("{pad}/* ACCEPT {c_target} */\n"));
        }
        HirStatement::Sort { file_name, .. } => {
            let c_name = sanitize_name(file_name);
            out.push_str(&format!("{pad}/* SORT {c_name} */\n"));
        }
        HirStatement::StopRun { .. } => {
            out.push_str(&format!("{pad}cobol_stop_run();\n"));
        }
        HirStatement::Goback { .. } => {
            out.push_str(&format!("{pad}cobol_goback();\n"));
        }
        HirStatement::Continue { .. } => {
            out.push_str(&format!("{pad}/* CONTINUE */\n"));
        }
        // --- COBOL 2002+ statements ---
        HirStatement::Invoke {
            object,
            method,
            params,
            returning,
            ..
        } => {
            let c_obj = emit_expr(object);
            let args: Vec<_> = params.iter().map(emit_expr).collect();
            let args_str = args.join(", ");
            if let Some(ret) = returning {
                let c_ret = sanitize_name(ret);
                out.push_str(&format!(
                    "{pad}{c_ret} = cobol_invoke(&{c_obj}, \"{method}\", (int64_t[]){{{args_str}}}, {});\n",
                    params.len()
                ));
            } else {
                out.push_str(&format!(
                    "{pad}cobol_invoke(&{c_obj}, \"{method}\", (int64_t[]){{{args_str}}}, {});\n",
                    params.len()
                ));
            }
        }
        HirStatement::Raise { exception, .. } => {
            out.push_str(&format!("{pad}cobol_raise(\"{exception}\");\n"));
        }
        HirStatement::Resume { target, .. } => {
            if let Some(t) = target {
                let c_target = sanitize_name(t);
                out.push_str(&format!("{pad}cobol_resume(\"{c_target}\");\n"));
            } else {
                out.push_str(&format!("{pad}cobol_resume(NULL);\n"));
            }
        }
        HirStatement::Allocate {
            target, returning, ..
        } => {
            let c_target = sanitize_name(target);
            if let Some(ret) = returning {
                let c_ret = sanitize_name(ret);
                out.push_str(&format!(
                    "{pad}{c_ret} = malloc(sizeof({c_target})); /* ALLOCATE */\n"
                ));
            } else {
                out.push_str(&format!(
                    "{pad}{c_target} = malloc(sizeof({c_target})); /* ALLOCATE */\n"
                ));
            }
        }
        HirStatement::Free { targets, .. } => {
            for target in targets {
                let c_target = sanitize_name(target);
                out.push_str(&format!("{pad}free({c_target}); {c_target} = NULL;\n"));
            }
        }
        // --- COBOL 2014+ statements ---
        HirStatement::Validate { target, .. } => {
            let c_target = sanitize_name(target);
            out.push_str(&format!(
                "{pad}cobol_validate(\"{c_target}\"); /* VALIDATE */\n"
            ));
        }
        HirStatement::JsonGenerate { source, target, .. } => {
            let c_source = sanitize_name(source);
            let c_target = sanitize_name(target);
            out.push_str(&format!(
                "{pad}cobol_json_generate(&{c_source}, sizeof({c_source}), (uint8_t*){c_target}, sizeof({c_target})); /* JSON GENERATE */\n"
            ));
        }
        HirStatement::JsonParse { source, target, .. } => {
            let c_source = sanitize_name(source);
            let c_target = sanitize_name(target);
            out.push_str(&format!(
                "{pad}cobol_json_parse((const uint8_t*){c_source}, strlen({c_source}), &{c_target}, sizeof({c_target})); /* JSON PARSE */\n"
            ));
        }
        HirStatement::XmlGenerate { source, target, .. } => {
            let c_source = sanitize_name(source);
            let c_target = sanitize_name(target);
            out.push_str(&format!(
                "{pad}cobol_xml_generate(&{c_source}, sizeof({c_source}), \"{c_source}\", {}, (uint8_t*){c_target}, sizeof({c_target})); /* XML GENERATE */\n",
                c_source.len()
            ));
        }
        HirStatement::XmlParse {
            source,
            processing_procedure,
            ..
        } => {
            let c_source = sanitize_name(source);
            let c_proc = sanitize_name(processing_procedure);
            out.push_str(&format!(
                "{pad}/* XML PARSE {c_source} PROCESSING PROCEDURE {c_proc} */\n"
            ));
        }
    }
}

fn emit_display_operand(out: &mut String, expr: &HirExpr, pad: &str) {
    match expr {
        HirExpr::Literal(HirLiteral::String(s)) => {
            let escaped = escape_c_string(s);
            let len = s.len();
            out.push_str(&format!(
                "{pad}cobol_display_string((const uint8_t*)\"{escaped}\", {len});\n"
            ));
        }
        HirExpr::Literal(HirLiteral::Integer(n)) => {
            out.push_str(&format!("{pad}cobol_display_int({n});\n"));
        }
        HirExpr::Literal(HirLiteral::Zero) => {
            out.push_str(&format!("{pad}cobol_display_int(0);\n"));
        }
        HirExpr::Literal(HirLiteral::Space) => {
            out.push_str(&format!("{pad}cobol_display_space();\n"));
        }
        HirExpr::Literal(HirLiteral::Decimal(d)) => {
            let escaped = escape_c_string(d);
            let len = d.len();
            out.push_str(&format!(
                "{pad}cobol_display_string((const uint8_t*)\"{escaped}\", {len});\n"
            ));
        }
        HirExpr::Variable(name) => {
            let c_name = sanitize_name(name);
            // We don't know the type at this point, so generate a generic display.
            // For simplicity, display as integer. A full implementation would
            // look up the type.
            out.push_str(&format!("{pad}cobol_display_int({c_name});\n"));
        }
        HirExpr::BinaryOp { .. } | HirExpr::UnaryOp { .. } => {
            let e = emit_expr(expr);
            out.push_str(&format!("{pad}cobol_display_int({e});\n"));
        }
    }
}

fn emit_move_to(out: &mut String, from: &HirExpr, c_target: &str, pad: &str) {
    // Simplified move: assign value to target
    match from {
        HirExpr::Literal(HirLiteral::String(s)) => {
            let escaped = escape_c_string(s);
            out.push_str(&format!(
                "{pad}strncpy({c_target}, \"{escaped}\", sizeof({c_target}) - 1);\n"
            ));
            out.push_str(&format!(
                "{pad}{c_target}[sizeof({c_target}) - 1] = '\\0';\n"
            ));
        }
        HirExpr::Literal(HirLiteral::Integer(n)) => {
            out.push_str(&format!("{pad}{c_target} = {n};\n"));
        }
        HirExpr::Literal(HirLiteral::Zero) => {
            out.push_str(&format!("{pad}{c_target} = 0;\n"));
        }
        HirExpr::Literal(HirLiteral::Space) => {
            out.push_str(&format!(
                "{pad}memset({c_target}, ' ', sizeof({c_target}) - 1);\n"
            ));
            out.push_str(&format!(
                "{pad}{c_target}[sizeof({c_target}) - 1] = '\\0';\n"
            ));
        }
        _ => {
            let e = emit_expr(from);
            out.push_str(&format!("{pad}{c_target} = {e};\n"));
        }
    }
}

fn emit_perform(out: &mut String, kind: &HirPerformKind, indent: usize) {
    let pad = "    ".repeat(indent);
    match kind {
        HirPerformKind::Inline { body } => {
            out.push_str(&format!("{pad}{{\n"));
            for s in body {
                emit_statement(out, s, indent + 1);
            }
            out.push_str(&format!("{pad}}}\n"));
        }
        HirPerformKind::Times { count, body } => {
            let c_count = emit_expr(count);
            out.push_str(&format!(
                "{pad}for (int64_t _cobol_i = 0; _cobol_i < ({c_count}); _cobol_i++) {{\n"
            ));
            for s in body {
                emit_statement(out, s, indent + 1);
            }
            out.push_str(&format!("{pad}}}\n"));
        }
        HirPerformKind::Until { condition, body } => {
            let cond = emit_condition(condition);
            out.push_str(&format!("{pad}while (!({cond})) {{\n"));
            for s in body {
                emit_statement(out, s, indent + 1);
            }
            out.push_str(&format!("{pad}}}\n"));
        }
        HirPerformKind::Varying {
            var,
            from,
            by,
            until,
            body,
        } => {
            let c_var = sanitize_name(var);
            let c_from = emit_expr(from);
            let c_by = emit_expr(by);
            let cond = emit_condition(until);
            out.push_str(&format!(
                "{pad}{c_var} = {c_from};\n{pad}while (!({cond})) {{\n"
            ));
            for s in body {
                emit_statement(out, s, indent + 1);
            }
            out.push_str(&format!("{pad}    {c_var} += {c_by};\n"));
            out.push_str(&format!("{pad}}}\n"));
        }
        HirPerformKind::ProcedureName { name } => {
            let c_name = sanitize_name(name);
            out.push_str(&format!(
                "{pad}/* PERFORM {c_name} -- procedure calls not yet implemented */\n"
            ));
        }
    }
}

fn emit_expr(expr: &HirExpr) -> String {
    match expr {
        HirExpr::Literal(HirLiteral::Integer(n)) => format!("((int64_t){n})"),
        HirExpr::Literal(HirLiteral::Decimal(d)) => d.to_string(),
        HirExpr::Literal(HirLiteral::String(s)) => {
            // Strings in expression context are unusual; use 0
            format!("0 /* string literal: {} */", escape_c_string(s))
        }
        HirExpr::Literal(HirLiteral::Zero) => "((int64_t)0)".to_string(),
        HirExpr::Literal(HirLiteral::Space) => "((int64_t)32)".to_string(),
        HirExpr::Variable(name) => sanitize_name(name),
        HirExpr::BinaryOp { op, left, right } => {
            let l = emit_expr(left);
            let r = emit_expr(right);
            let op_str = match op {
                HirBinOp::Add => "+",
                HirBinOp::Sub => "-",
                HirBinOp::Mul => "*",
                HirBinOp::Div => "/",
                HirBinOp::Pow => return format!("/* pow */ (int64_t)1 /* {l} ** {r} */"),
            };
            format!("({l} {op_str} {r})")
        }
        HirExpr::UnaryOp { op, operand } => {
            let o = emit_expr(operand);
            match op {
                HirUnaryOp::Neg => format!("(-{o})"),
            }
        }
    }
}

fn emit_condition(cond: &HirCondition) -> String {
    match cond {
        HirCondition::Compare { left, op, right } => {
            let l = emit_expr(left);
            let r = emit_expr(right);
            let op_str = match op {
                HirCompareOp::Eq => "==",
                HirCompareOp::Ne => "!=",
                HirCompareOp::Gt => ">",
                HirCompareOp::Lt => "<",
                HirCompareOp::Ge => ">=",
                HirCompareOp::Le => "<=",
            };
            format!("({l} {op_str} {r})")
        }
        HirCondition::And(a, b) => {
            let a = emit_condition(a);
            let b = emit_condition(b);
            format!("({a} && {b})")
        }
        HirCondition::Or(a, b) => {
            let a = emit_condition(a);
            let b = emit_condition(b);
            format!("({a} || {b})")
        }
        HirCondition::Not(inner) => {
            let c = emit_condition(inner);
            format!("(!{c})")
        }
    }
}

/// Convert a COBOL data name to a valid C identifier.
///
/// COBOL names use hyphens which are not valid in C, so we replace
/// them with underscores.
fn sanitize_name(name: &str) -> String {
    name.replace('-', "_")
}

/// Escape special characters for use in a C string literal.
fn escape_c_string(s: &str) -> String {
    let mut escaped = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '\\' => escaped.push_str("\\\\"),
            '"' => escaped.push_str("\\\""),
            '\n' => escaped.push_str("\\n"),
            '\r' => escaped.push_str("\\r"),
            '\t' => escaped.push_str("\\t"),
            '\0' => escaped.push_str("\\0"),
            c => escaped.push(c),
        }
    }
    escaped
}

// ---------------------------------------------------------------------------
// COBOL 2002+: Class and function code generation
// ---------------------------------------------------------------------------

fn emit_classes(out: &mut String, classes: &[cobol_hir::HirClass]) {
    for class in classes {
        let c_name = sanitize_name(&class.name);
        out.push_str(&format!("/* CLASS {} */\n", c_name));

        // Emit instance data as a struct
        out.push_str(&format!("typedef struct {c_name}_s {{\n"));
        out.push_str("    void* _vtable; /* vtable pointer */\n");
        for item in &class.instance_data {
            let member_name = sanitize_name(&item.name);
            let c_type = hir_type_to_c(&item.data_type);
            out.push_str(&format!("    {c_type} {member_name};\n"));
        }
        out.push_str(&format!("}} {c_name};\n\n"));

        // Emit vtable struct
        out.push_str(&format!("typedef struct {c_name}_vtable_s {{\n"));
        for method in &class.instance_methods {
            let method_name = sanitize_name(&method.name);
            out.push_str(&format!("    int64_t (*{method_name})({c_name}* self);\n"));
        }
        out.push_str(&format!("}} {c_name}_vtable;\n\n"));

        // Emit method implementations
        for method in &class.instance_methods {
            let method_name = sanitize_name(&method.name);
            out.push_str(&format!(
                "int64_t {c_name}_{method_name}({c_name}* self) {{\n"
            ));
            for item in &method.data_items {
                let local_name = sanitize_name(&item.name);
                let c_type = hir_type_to_c(&item.data_type);
                out.push_str(&format!("    {c_type} {local_name};\n"));
            }
            for stmt in &method.body {
                emit_statement(out, stmt, 1);
            }
            out.push_str("    return 0;\n");
            out.push_str("}\n\n");
        }

        // Emit factory methods
        for method in &class.factory_methods {
            let method_name = sanitize_name(&method.name);
            out.push_str(&format!(
                "int64_t {c_name}_factory_{method_name}(void) {{\n"
            ));
            for stmt in &method.body {
                emit_statement(out, stmt, 1);
            }
            out.push_str("    return 0;\n");
            out.push_str("}\n\n");
        }

        // Emit vtable instance
        out.push_str(&format!(
            "static {c_name}_vtable {c_name}_vtable_instance = {{\n"
        ));
        for method in &class.instance_methods {
            let method_name = sanitize_name(&method.name);
            out.push_str(&format!("    .{method_name} = {c_name}_{method_name},\n"));
        }
        out.push_str("};\n\n");

        // Emit constructor (NEW)
        out.push_str(&format!("{c_name}* {c_name}_new(void) {{\n"));
        out.push_str(&format!(
            "    {c_name}* obj = ({c_name}*)malloc(sizeof({c_name}));\n"
        ));
        out.push_str(&format!("    obj->_vtable = &{c_name}_vtable_instance;\n"));
        out.push_str("    return obj;\n");
        out.push_str("}\n\n");
    }
}

fn emit_functions(out: &mut String, functions: &[cobol_hir::HirFunction]) {
    for func in functions {
        let c_name = sanitize_name(&func.name);
        let ret_type = hir_type_to_c(&func.returning);

        // Build parameter list
        let params: Vec<String> = func
            .params
            .iter()
            .map(|p| {
                let p_name = sanitize_name(&p.name);
                let p_type = hir_type_to_c(&p.data_type);
                format!("{p_type} {p_name}")
            })
            .collect();
        let params_str = if params.is_empty() {
            "void".to_string()
        } else {
            params.join(", ")
        };

        out.push_str(&format!(
            "{ret_type} cobol_func_{c_name}({params_str}) {{\n"
        ));

        // Local data items
        for item in &func.data_items {
            let local_name = sanitize_name(&item.name);
            let c_type = hir_type_to_c(&item.data_type);
            out.push_str(&format!("    {c_type} {local_name};\n"));
        }
        emit_data_init(out, &func.data_items);

        // Body
        for stmt in &func.body {
            emit_statement(out, stmt, 1);
        }

        out.push_str(&format!("    return ({ret_type})0;\n"));
        out.push_str("}\n\n");
    }
}

fn emit_typedefs(out: &mut String, typedefs: &[cobol_hir::HirTypedef]) {
    for td in typedefs {
        let c_name = sanitize_name(&td.name);
        let c_type = hir_type_to_c(&td.base_type);
        out.push_str(&format!("typedef {c_type} {c_name}; /* TYPEDEF */\n"));
    }
    if !typedefs.is_empty() {
        out.push('\n');
    }
}

fn emit_interfaces(out: &mut String, interfaces: &[cobol_hir::HirInterface]) {
    for iface in interfaces {
        let c_name = sanitize_name(&iface.name);
        out.push_str(&format!("/* INTERFACE {} */\n", c_name));

        // Emit interface as a vtable struct
        out.push_str(&format!("typedef struct {c_name}_vtable_s {{\n"));
        for method in &iface.methods {
            let method_name = sanitize_name(&method.name);
            out.push_str(&format!("    int64_t (*{method_name})(void* self);\n"));
        }
        out.push_str(&format!("}} {c_name}_vtable;\n\n"));
    }
}

/// Map a HIR type to its C representation.
fn hir_type_to_c(data_type: &HirType) -> &'static str {
    match data_type {
        HirType::Alphanumeric { .. } => "char*",
        HirType::Numeric { .. } => "int64_t",
        HirType::Group { .. } => "int64_t",
        HirType::Comp3 { .. } => "int64_t",
        HirType::Binary { .. } => "int64_t",
        HirType::Index => "int64_t",
        HirType::Pointer => "void*",
        HirType::Boolean => "int8_t",
        HirType::FloatShort => "float",
        HirType::FloatLong => "double",
        HirType::FloatExtended => "long double",
    }
}

/// Compile a generated C source file into a native executable.
///
/// Returns `Ok(())` on success, or an error message on failure.
pub fn compile_c_to_executable(
    c_source_path: &std::path::Path,
    output_path: &std::path::Path,
    runtime_lib_path: &std::path::Path,
) -> Result<(), String> {
    // Try clang first, then cc
    let compiler = find_c_compiler()?;

    let status = std::process::Command::new(&compiler)
        .arg(c_source_path)
        .arg("-o")
        .arg(output_path)
        .arg(format!("-L{}", runtime_lib_path.display()))
        .arg("-lcobol_runtime")
        .arg("-lpthread")
        .arg("-ldl")
        .arg("-lm")
        .status()
        .map_err(|e| format!("Failed to run C compiler '{}': {}", compiler, e))?;

    if status.success() {
        Ok(())
    } else {
        Err(format!(
            "C compiler '{}' exited with status: {}",
            compiler, status
        ))
    }
}

fn find_c_compiler() -> Result<String, String> {
    // Check CC environment variable
    if let Ok(cc) = std::env::var("CC") {
        return Ok(cc);
    }

    // Try clang, then gcc, then cc
    for compiler in &["clang", "gcc", "cc"] {
        if std::process::Command::new(compiler)
            .arg("--version")
            .output()
            .is_ok()
        {
            return Ok(compiler.to_string());
        }
    }

    Err("No C compiler found. Install clang or gcc.".to_string())
}

#[cfg(test)]
mod tests {
    use super::*;
    use cobol_common::{FileId, SourceFormat};
    use cobol_hir::lower_to_hir;
    use cobol_lexer::Lexer;
    use cobol_parser::Parser;

    fn parse_lower_generate(source: &str) -> String {
        let mut lexer = Lexer::new(source, FileId(0), SourceFormat::Free);
        let tokens = lexer.lex_all();
        let mut parser = Parser::new(tokens, FileId(0));
        let program = parser.parse_program().unwrap();
        let hir = lower_to_hir(&program);
        generate_c(&hir)
    }

    #[test]
    fn test_generate_hello_world() {
        let src = "\
IDENTIFICATION DIVISION.
PROGRAM-ID. HELLO-WORLD.
PROCEDURE DIVISION.
    DISPLAY \"Hello, World!\".
    STOP RUN.
";
        let c_code = parse_lower_generate(src);
        assert!(c_code.contains("cobol_display_string"));
        assert!(c_code.contains("Hello, World!"));
        assert!(c_code.contains("cobol_display_newline"));
        assert!(c_code.contains("cobol_stop_run"));
        assert!(c_code.contains("int main"));
    }

    #[test]
    fn test_generate_with_data_items() {
        let src = "\
IDENTIFICATION DIVISION.
PROGRAM-ID. TEST-DATA.
DATA DIVISION.
WORKING-STORAGE SECTION.
01  WS-NAME PIC X(20).
01  WS-COUNT PIC 9(5).
PROCEDURE DIVISION.
    DISPLAY WS-COUNT.
    STOP RUN.
";
        let c_code = parse_lower_generate(src);
        assert!(c_code.contains("static char WS_NAME"));
        assert!(c_code.contains("static int64_t WS_COUNT"));
    }

    #[test]
    fn test_sanitize_name() {
        assert_eq!(sanitize_name("WS-NAME"), "WS_NAME");
        assert_eq!(sanitize_name("HELLO-WORLD"), "HELLO_WORLD");
        assert_eq!(sanitize_name("SIMPLE"), "SIMPLE");
    }

    #[test]
    fn test_escape_c_string() {
        assert_eq!(escape_c_string("hello"), "hello");
        assert_eq!(escape_c_string("say \"hi\""), "say \\\"hi\\\"");
        assert_eq!(escape_c_string("a\\b"), "a\\\\b");
    }

    #[test]
    fn test_generate_if_statement() {
        let src = "\
IDENTIFICATION DIVISION.
PROGRAM-ID. TEST-IF.
DATA DIVISION.
WORKING-STORAGE SECTION.
01  WS-A PIC 9(3).
PROCEDURE DIVISION.
    IF WS-A > 100
        DISPLAY \"BIG\"
    ELSE
        DISPLAY \"SMALL\"
    END-IF.
    STOP RUN.
";
        let c_code = parse_lower_generate(src);
        assert!(c_code.contains("if ("));
        assert!(c_code.contains("} else {"));
    }

    // -----------------------------------------------------------------------
    // COBOL 2002+ codegen tests
    // -----------------------------------------------------------------------

    #[test]
    fn test_generate_raise() {
        let src = "\
IDENTIFICATION DIVISION.
PROGRAM-ID. TEST-RAISE.
PROCEDURE DIVISION.
    RAISE EXCEPTION \"EC-SIZE-OVERFLOW\".
    STOP RUN.
";
        let c_code = parse_lower_generate(src);
        assert!(
            c_code.contains("cobol_raise"),
            "Generated C should contain cobol_raise call"
        );
    }

    #[test]
    fn test_generate_resume() {
        let src = "\
IDENTIFICATION DIVISION.
PROGRAM-ID. TEST-RESUME.
PROCEDURE DIVISION.
    RESUME.
    STOP RUN.
";
        let c_code = parse_lower_generate(src);
        assert!(
            c_code.contains("cobol_resume"),
            "Generated C should contain cobol_resume call"
        );
    }

    #[test]
    fn test_generate_invoke() {
        let src = "\
IDENTIFICATION DIVISION.
PROGRAM-ID. TEST-INVOKE.
DATA DIVISION.
WORKING-STORAGE SECTION.
01  MY-OBJ USAGE POINTER.
01  MY-RESULT PIC 9(5).
PROCEDURE DIVISION.
    INVOKE MY-OBJ \"DO-SOMETHING\" RETURNING MY-RESULT.
    STOP RUN.
";
        let c_code = parse_lower_generate(src);
        assert!(
            c_code.contains("cobol_invoke"),
            "Generated C should contain cobol_invoke call"
        );
        assert!(
            c_code.contains("DO-SOMETHING"),
            "Generated C should reference the method name"
        );
    }

    #[test]
    fn test_generate_allocate_and_free() {
        let src = "\
IDENTIFICATION DIVISION.
PROGRAM-ID. TEST-ALLOC.
DATA DIVISION.
WORKING-STORAGE SECTION.
01  MY-PTR USAGE POINTER.
PROCEDURE DIVISION.
    ALLOCATE MY-PTR.
    FREE MY-PTR.
    STOP RUN.
";
        let c_code = parse_lower_generate(src);
        assert!(
            c_code.contains("malloc"),
            "Generated C should contain malloc for ALLOCATE"
        );
        assert!(
            c_code.contains("free("),
            "Generated C should contain free for FREE"
        );
    }

    #[test]
    fn test_generate_setjmp_header() {
        let src = "\
IDENTIFICATION DIVISION.
PROGRAM-ID. TEST-HDR.
PROCEDURE DIVISION.
    STOP RUN.
";
        let c_code = parse_lower_generate(src);
        assert!(
            c_code.contains("#include <setjmp.h>"),
            "Generated C should include setjmp.h"
        );
    }

    #[test]
    fn test_generate_runtime_declarations_2002() {
        let src = "\
IDENTIFICATION DIVISION.
PROGRAM-ID. TEST-DECL.
PROCEDURE DIVISION.
    STOP RUN.
";
        let c_code = parse_lower_generate(src);
        assert!(
            c_code.contains("cobol_raise"),
            "Runtime declarations should include cobol_raise"
        );
        assert!(
            c_code.contains("cobol_resume"),
            "Runtime declarations should include cobol_resume"
        );
        assert!(
            c_code.contains("cobol_invoke"),
            "Runtime declarations should include cobol_invoke"
        );
    }

    #[test]
    fn test_generate_class_struct() {
        use cobol_common::Span;

        let hir = HirProgram {
            name: "TEST-CLASS".into(),
            data_items: Vec::new(),
            paragraphs: Vec::new(),
            body: Vec::new(),
            classes: vec![cobol_hir::HirClass {
                name: "MY-CLASS".into(),
                parent: None,
                factory_methods: Vec::new(),
                instance_methods: vec![cobol_hir::HirMethod {
                    name: "DO-WORK".into(),
                    params: Vec::new(),
                    returning: None,
                    data_items: Vec::new(),
                    body: Vec::new(),
                    span: Span::dummy(),
                }],
                factory_data: Vec::new(),
                instance_data: vec![HirDataItem {
                    name: "MY-FIELD".into(),
                    data_type: HirType::Numeric {
                        size: 5,
                        decimal_places: 0,
                        is_signed: false,
                    },
                    initial_value: None,
                    span: Span::dummy(),
                }],
                span: Span::dummy(),
            }],
            functions: Vec::new(),
            typedefs: Vec::new(),
            interfaces: Vec::new(),
            span: Span::dummy(),
        };

        let c_code = generate_c(&hir);
        assert!(
            c_code.contains("typedef struct MY_CLASS_s"),
            "Should generate struct for class"
        );
        assert!(c_code.contains("_vtable"), "Should generate vtable");
        assert!(
            c_code.contains("MY_CLASS_new"),
            "Should generate constructor"
        );
        assert!(
            c_code.contains("MY_CLASS_DO_WORK"),
            "Should generate method implementation"
        );
    }

    #[test]
    fn test_generate_function() {
        use cobol_common::Span;

        let hir = HirProgram {
            name: "TEST-FUNC".into(),
            data_items: Vec::new(),
            paragraphs: Vec::new(),
            body: Vec::new(),
            classes: Vec::new(),
            functions: vec![cobol_hir::HirFunction {
                name: "ADD-NUMBERS".into(),
                params: vec![
                    cobol_hir::HirParam {
                        name: "A".into(),
                        mode: cobol_hir::HirParamMode::ByValue,
                        data_type: HirType::Numeric {
                            size: 5,
                            decimal_places: 0,
                            is_signed: false,
                        },
                    },
                    cobol_hir::HirParam {
                        name: "B".into(),
                        mode: cobol_hir::HirParamMode::ByValue,
                        data_type: HirType::Numeric {
                            size: 5,
                            decimal_places: 0,
                            is_signed: false,
                        },
                    },
                ],
                returning: HirType::Numeric {
                    size: 5,
                    decimal_places: 0,
                    is_signed: false,
                },
                data_items: Vec::new(),
                body: Vec::new(),
                span: Span::dummy(),
            }],
            typedefs: Vec::new(),
            interfaces: Vec::new(),
            span: Span::dummy(),
        };

        let c_code = generate_c(&hir);
        assert!(
            c_code.contains("cobol_func_ADD_NUMBERS"),
            "Should generate function with cobol_func_ prefix"
        );
        assert!(c_code.contains("int64_t A"), "Should generate parameter A");
        assert!(c_code.contains("int64_t B"), "Should generate parameter B");
    }

    #[test]
    fn test_hir_type_to_c_boolean() {
        assert_eq!(hir_type_to_c(&HirType::Boolean), "int8_t");
    }

    #[test]
    fn test_generate_local_storage() {
        let src = "\
IDENTIFICATION DIVISION.
PROGRAM-ID. TEST-LOCAL.
DATA DIVISION.
LOCAL-STORAGE SECTION.
01  LS-COUNTER PIC 9(5) VALUE 0.
WORKING-STORAGE SECTION.
01  WS-COUNTER PIC 9(5) VALUE 0.
PROCEDURE DIVISION.
    ADD 1 TO LS-COUNTER.
    ADD 1 TO WS-COUNTER.
    STOP RUN.
";
        let c_code = parse_lower_generate(src);
        assert!(
            c_code.contains("LS_COUNTER"),
            "Should emit LOCAL-STORAGE variable"
        );
        assert!(
            c_code.contains("WS_COUNTER"),
            "Should emit WORKING-STORAGE variable"
        );
    }

    // -----------------------------------------------------------------------
    // COBOL 2014+ codegen tests
    // -----------------------------------------------------------------------

    #[test]
    fn test_generate_float_short() {
        let src = "\
IDENTIFICATION DIVISION.
PROGRAM-ID. TEST-FLOAT.
DATA DIVISION.
WORKING-STORAGE SECTION.
01  WS-FLOAT USAGE FLOAT-SHORT.
PROCEDURE DIVISION.
    STOP RUN.
";
        let c_code = parse_lower_generate(src);
        assert!(
            c_code.contains("static float WS_FLOAT"),
            "FLOAT-SHORT should generate C float type"
        );
    }

    #[test]
    fn test_generate_float_long() {
        let src = "\
IDENTIFICATION DIVISION.
PROGRAM-ID. TEST-FLOAT-L.
DATA DIVISION.
WORKING-STORAGE SECTION.
01  WS-FLOAT-L USAGE FLOAT-LONG.
PROCEDURE DIVISION.
    STOP RUN.
";
        let c_code = parse_lower_generate(src);
        assert!(
            c_code.contains("static double WS_FLOAT_L"),
            "FLOAT-LONG should generate C double type"
        );
    }

    #[test]
    fn test_generate_float_extended() {
        let src = "\
IDENTIFICATION DIVISION.
PROGRAM-ID. TEST-FLOAT-E.
DATA DIVISION.
WORKING-STORAGE SECTION.
01  WS-FLOAT-E USAGE FLOAT-EXTENDED.
PROCEDURE DIVISION.
    STOP RUN.
";
        let c_code = parse_lower_generate(src);
        assert!(
            c_code.contains("static long double WS_FLOAT_E"),
            "FLOAT-EXTENDED should generate C long double type"
        );
    }

    #[test]
    fn test_generate_float_init() {
        let src = "\
IDENTIFICATION DIVISION.
PROGRAM-ID. TEST-FLOAT-INIT.
DATA DIVISION.
WORKING-STORAGE SECTION.
01  WS-F USAGE FLOAT-SHORT.
PROCEDURE DIVISION.
    STOP RUN.
";
        let c_code = parse_lower_generate(src);
        assert!(
            c_code.contains("WS_F = 0.0"),
            "Float data items should be initialized to 0.0"
        );
    }

    #[test]
    fn test_hir_type_to_c_float_short() {
        assert_eq!(hir_type_to_c(&HirType::FloatShort), "float");
    }

    #[test]
    fn test_hir_type_to_c_float_long() {
        assert_eq!(hir_type_to_c(&HirType::FloatLong), "double");
    }

    #[test]
    fn test_hir_type_to_c_float_extended() {
        assert_eq!(hir_type_to_c(&HirType::FloatExtended), "long double");
    }

    #[test]
    fn test_generate_validate_statement() {
        use cobol_common::Span;

        let hir = HirProgram {
            name: "TEST-VALIDATE".into(),
            data_items: vec![HirDataItem {
                name: "WS-NAME".into(),
                data_type: HirType::Alphanumeric { size: 20 },
                initial_value: None,
                span: Span::dummy(),
            }],
            paragraphs: Vec::new(),
            body: vec![HirStatement::Validate {
                target: "WS-NAME".into(),
                span: Span::dummy(),
            }],
            classes: Vec::new(),
            functions: Vec::new(),
            typedefs: Vec::new(),
            interfaces: Vec::new(),
            span: Span::dummy(),
        };

        let c_code = generate_c(&hir);
        assert!(
            c_code.contains("cobol_validate"),
            "VALIDATE should generate cobol_validate call"
        );
    }

    #[test]
    fn test_generate_json_generate_statement() {
        use cobol_common::Span;

        let hir = HirProgram {
            name: "TEST-JSON-GEN".into(),
            data_items: Vec::new(),
            paragraphs: Vec::new(),
            body: vec![HirStatement::JsonGenerate {
                source: "WS-DATA".into(),
                target: "WS-JSON".into(),
                span: Span::dummy(),
            }],
            classes: Vec::new(),
            functions: Vec::new(),
            typedefs: Vec::new(),
            interfaces: Vec::new(),
            span: Span::dummy(),
        };

        let c_code = generate_c(&hir);
        assert!(
            c_code.contains("cobol_json_generate"),
            "JSON GENERATE should emit cobol_json_generate call"
        );
    }

    #[test]
    fn test_generate_json_parse_statement() {
        use cobol_common::Span;

        let hir = HirProgram {
            name: "TEST-JSON-PARSE".into(),
            data_items: Vec::new(),
            paragraphs: Vec::new(),
            body: vec![HirStatement::JsonParse {
                source: "WS-JSON".into(),
                target: "WS-DATA".into(),
                span: Span::dummy(),
            }],
            classes: Vec::new(),
            functions: Vec::new(),
            typedefs: Vec::new(),
            interfaces: Vec::new(),
            span: Span::dummy(),
        };

        let c_code = generate_c(&hir);
        assert!(
            c_code.contains("cobol_json_parse"),
            "JSON PARSE should emit cobol_json_parse call"
        );
    }

    #[test]
    fn test_generate_xml_generate_statement() {
        use cobol_common::Span;

        let hir = HirProgram {
            name: "TEST-XML-GEN".into(),
            data_items: Vec::new(),
            paragraphs: Vec::new(),
            body: vec![HirStatement::XmlGenerate {
                source: "WS-DATA".into(),
                target: "WS-XML".into(),
                span: Span::dummy(),
            }],
            classes: Vec::new(),
            functions: Vec::new(),
            typedefs: Vec::new(),
            interfaces: Vec::new(),
            span: Span::dummy(),
        };

        let c_code = generate_c(&hir);
        assert!(
            c_code.contains("cobol_xml_generate"),
            "XML GENERATE should emit cobol_xml_generate call"
        );
    }

    #[test]
    fn test_generate_xml_parse_statement() {
        use cobol_common::Span;

        let hir = HirProgram {
            name: "TEST-XML-PARSE".into(),
            data_items: Vec::new(),
            paragraphs: Vec::new(),
            body: vec![HirStatement::XmlParse {
                source: "WS-XML".into(),
                processing_procedure: "XML-HANDLER".into(),
                span: Span::dummy(),
            }],
            classes: Vec::new(),
            functions: Vec::new(),
            typedefs: Vec::new(),
            interfaces: Vec::new(),
            span: Span::dummy(),
        };

        let c_code = generate_c(&hir);
        assert!(
            c_code.contains("XML PARSE"),
            "XML PARSE should emit XML PARSE comment"
        );
        assert!(
            c_code.contains("XML_HANDLER"),
            "XML PARSE should reference processing procedure"
        );
    }

    #[test]
    fn test_generate_typedef() {
        use cobol_common::Span;

        let hir = HirProgram {
            name: "TEST-TYPEDEF".into(),
            data_items: Vec::new(),
            paragraphs: Vec::new(),
            body: Vec::new(),
            classes: Vec::new(),
            functions: Vec::new(),
            typedefs: vec![cobol_hir::HirTypedef {
                name: "MONEY-TYPE".into(),
                base_type: HirType::Numeric {
                    size: 9,
                    decimal_places: 2,
                    is_signed: true,
                },
                span: Span::dummy(),
            }],
            interfaces: Vec::new(),
            span: Span::dummy(),
        };

        let c_code = generate_c(&hir);
        assert!(
            c_code.contains("typedef int64_t MONEY_TYPE"),
            "TYPEDEF should generate C typedef"
        );
    }

    #[test]
    fn test_generate_interface() {
        use cobol_common::Span;

        let hir = HirProgram {
            name: "TEST-IFACE".into(),
            data_items: Vec::new(),
            paragraphs: Vec::new(),
            body: Vec::new(),
            classes: Vec::new(),
            functions: Vec::new(),
            typedefs: Vec::new(),
            interfaces: vec![cobol_hir::HirInterface {
                name: "IComparable".into(),
                methods: vec![cobol_hir::HirMethod {
                    name: "CompareTo".into(),
                    params: Vec::new(),
                    returning: None,
                    data_items: Vec::new(),
                    body: Vec::new(),
                    span: Span::dummy(),
                }],
                span: Span::dummy(),
            }],
            span: Span::dummy(),
        };

        let c_code = generate_c(&hir);
        assert!(
            c_code.contains("INTERFACE IComparable"),
            "Should generate interface comment"
        );
        assert!(
            c_code.contains("IComparable_vtable"),
            "Should generate vtable for interface"
        );
        assert!(
            c_code.contains("CompareTo"),
            "Should include method in vtable"
        );
    }

    #[test]
    fn test_generate_runtime_declarations_2014() {
        let src = "\
IDENTIFICATION DIVISION.
PROGRAM-ID. TEST-DECL-2014.
PROCEDURE DIVISION.
    STOP RUN.
";
        let c_code = parse_lower_generate(src);
        assert!(
            c_code.contains("cobol_validate"),
            "Should declare cobol_validate"
        );
        assert!(
            c_code.contains("cobol_json_generate"),
            "Should declare cobol_json_generate"
        );
        assert!(
            c_code.contains("cobol_json_parse"),
            "Should declare cobol_json_parse"
        );
        assert!(
            c_code.contains("cobol_xml_generate"),
            "Should declare cobol_xml_generate"
        );
        assert!(
            c_code.contains("cobol_xml_parse"),
            "Should declare cobol_xml_parse"
        );
    }

    #[test]
    fn test_generate_runtime_declarations_2023() {
        let src = "\
IDENTIFICATION DIVISION.
PROGRAM-ID. TEST-DECL-2023.
PROCEDURE DIVISION.
    STOP RUN.
";
        let c_code = parse_lower_generate(src);
        assert!(
            c_code.contains("cobol_utf8_char_count"),
            "Should declare cobol_utf8_char_count"
        );
        assert!(
            c_code.contains("cobol_utf8_substring"),
            "Should declare cobol_utf8_substring"
        );
        assert!(
            c_code.contains("cobol_thread_create"),
            "Should declare cobol_thread_create"
        );
        assert!(
            c_code.contains("cobol_mutex_create"),
            "Should declare cobol_mutex_create"
        );
    }
}
